#makefile
#by
#date:

#Exemplo de uma make file

##nomeTarget:prerequisito1(all) prerequesito2(ala.c)
#<tab> comando

#all: aula.c - força o requesito que é o aula.c (ou seja, vais complilar na aula.c)	
all: aula.c 
	gcc -o all.exe aula.c
	
# se em vez de o "all:" colocarmos "outracoisa:"- ao fazer o "mingw32-make" outracoisa ele vai hiperligar ao código base em si
 